#!/bin/sh
# convert light colors to breeze-dark colors

find -name "*.svg" -o -name "*.SVG" | while read i;
do 
	fname=$( basename "$i")
	fdir=$( dirname "$i")
	#inkscape -f "$i" -e "${i%.*}.png"
	echo $fname
	sed -i -e 's/#00e5ff/#f2f2f2/g' "$i"
	sed -i -e 's/#eff0f1/#00e5ff/g' "$i"
	sed -i -e 's/#fcfcfc/#4f575f/g' "$i"
done 
