"""Predict_EEGNet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lt78Z2UIcZR-EvfWluTcxS7plX5O_uVJ
"""

import tensorflow as tf
import numpy as np

class Predict_EEGNet:

  def __init__(self, path_model):
    self.path_model = path_model
    self.model = tf.keras.models.load_model(path_model)

  def predict(self, X):
    y = self.model.predict(X)
    y = np.argmax(y)
    print(y)

    return y